dist: trusty

services:
 - docker

 
branches:
  only:
    - master


script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/ccsi-tf .
  - docker images
  - docker push $DOCKER_USERNAME/ccsi-tf